### ISSUE TITLE
failed to compile with ffmpeg >= 6.1

### ISSUE THREAD

**Issue by mokurin000** [gyunaev/karlyriceditor#22]
```
ffmpegvideoencoder.cpp: In member function 'bool FFMpegVideoEncoderPriv::createFile(const QString&)':
ffmpegvideoencoder.cpp:254:39: error: invalid conversion from 'const AVOutputFormat*' to 'AVOutputFormat*' [-fpermissive]
  254 |         outputFormat = av_guess_format( qPrintable( m_profile->videoContainer ), qPrintable( m_profile->videoContainer ), 0 );
      |                        ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                       |
      |                                       const AVOutputFormat*
ffmpegvideoencoder.cpp:274:50: error: invalid conversion from 'const AVCodec*' to 'AVCodec*' [-fpermissive]
  274 |         videoCodec = avcodec_find_encoder_by_name( qPrintable(m_profile->videoCodec) );
      |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                  |
      |                                                  const AVCodec*
ffmpegvideoencoder.cpp:373:50: error: invalid conversion from 'const AVCodec*' to 'AVCodec*' [-fpermissive]
  373 |         audioCodec = avcodec_find_encoder_by_name( qPrintable( m_profile->audioCodec ) );
      |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                  |
      |                                                  const AVCodec*
ffmpegvideoencoder.cpp:383:54: error: invalid conversion from 'const AVCodec*' to 'AVCodec*' [-fpermissive]
  383 |             audioCodec = avcodec_find_encoder_by_name( "ac3_fixed" );
      |                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
      |                                                      |
      |                                                      const AVCodec*
g++ -c -pipe -march=native -Ofast -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fno-plt -fopenmp -pthread -Wno-error -w -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -flto=auto -flto -fno-fat-lto-objects -Wall -Wextra -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -I/usr/include/ffmpeg -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I. -I. -I/usr/lib/qt/mkspecs/linux-g++ -o videogenerator.o videogenerator.cpp
g++ -c -pipe -march=native -Ofast -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fno-plt -fopenmp -pthread -Wno-error -w -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -flto=auto -flto -fno-fat-lto-objects -Wall -Wextra -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -I/usr/include/ffmpeg -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I. -I. -I/usr/lib/qt/mkspecs/linux-g++ -o lyricsevents.o lyricsevents.cpp
ffmpegvideodecoder.cpp: In member function 'bool FFMpegVideoDecoder::openFile(const QString&, unsigned int)':
ffmpegvideodecoder.cpp:107:44: error: invalid conversion from 'const AVCodec*' to 'AVCodec*' [-fpermissive]
  107 |         AVCodec *dec = avcodec_find_decoder( stream->codecpar->codec_id );
      |                        ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                            |
      |                                            const AVCodec*
make[1]: *** [Makefile:1316: ffmpegvideoencoder.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:1309: ffmpegvideodecoder.o] Error 1
make[1]: Leaving directory '/home/poly/.cache/paru/clone/karlyriceditor/src/karlyriceditor-3.2/src'
make: *** [Makefile:47: sub-src-make_first] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
error: failed to build 'karlyriceditor-3.2-1': 
error: packages failed to build: karlyriceditor-3.2-1

```

**Comment by meinwald** [comment]
I created #23 to address this.

**Comment by gyunaev** [comment]
4.0 no longer needs ffmpeg.
